version: '3.7'

services:
  servidor:
    image: fjortegan/dwes:laravel
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "80:80"
    # development
    volumes:
      - ./laravel:/var/www/html
    # Sólo en máquinas Linux, comentar estas dos líneas en otros sistemas de lusers
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mariadb
    #ports:
    #  - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql    
    environment:
      MYSQL_DATABASE: instagram
      MYSQL_USER: admin
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: pestillo

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

#  adminer:
#        image: adminer
#        ports:
#          - "8081:8080"    